version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db  # Use this name for pinging
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - root-data:/var/lib/mysql
    networks:
      - local-network

networks:
  local-network:
    name: laravel-network
    driver: bridge

volumes:
  root-data: