
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - root-data:/var/lib/mysql
    networks:
      - local-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-panel
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      # Use the container_name of your db service as the host
      - PMA_HOST=mysql-db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=64M
    networks:
      - local-network
    depends_on:
      - db

networks:
  local-network:
    external: true
    name: laravel-network

volumes:
  root-data: